"""Pandera schema for the mart_applicant_features contract - the boundary
between the dbt-built warehouse (SQL, untyped from Python's perspective)
and every Python consumer (EDA, modeling, serving, dashboard). Catches a
broken dbt model, a raw-data drift, or a schema change here, with a clear
column-level error, instead of as a confusing crash three modules
downstream (or worse, a model that silently trains on garbage).

Not an exhaustive per-column schema - the mart has ~130 feature columns,
mostly float ratios/averages that are legitimately nullable (no history to
average over - see the mart SQL's own comment on this). Two column
families have a real, checkable invariant regardless of which specific
feature it is:
  - the COALESCED_COUNT_COLUMNS below - explicitly `coalesce(x, 0)` in the
    mart SQL, so always a non-negative, non-null count. NOT every column
    ending in "_count" qualifies - bureau_credit_types_count, for one, is
    deliberately left NULL when an applicant has no bureau history (see
    the mart SQL), so it's excluded rather than swept in by a regex.
  - has_*_history flags, always `(x.sk_id_curr is not null)` in SQL, so
    always a non-null bool - these ARE safe to match by regex, since every
    column matching that name pattern is generated by that exact same
    expression.
"""

import pandera.pandas as pa

from home_credit import config

COALESCED_COUNT_COLUMNS = [
    "bureau_count",
    "bureau_active_count",
    "bureau_closed_count",
    "bureau_cnt_credit_prolong_sum",
    "prev_app_count",
    "prev_app_approved_count",
    "prev_app_refused_count",
    "prev_app_canceled_count",
    "prev_app_new_client_count",
    "pos_records_count",
    "pos_distinct_prev_count",
    "pos_completed_count",
    "pos_active_count",
    "cc_records_count",
    "cc_distinct_prev_count",
    "cc_underpaid_months_count",
    "inst_payments_count",
    "inst_distinct_prev_count",
]

MART_SCHEMA = pa.DataFrameSchema(
    columns={
        config.ID_COL: pa.Column(int, unique=True, nullable=False, checks=pa.Check.ge(0)),
        "is_train": pa.Column(bool, nullable=False),
        # TARGET is NULL for the scoring set (application_test) by design - see
        # stg_application.sql - so nullable=True; where present it must be 0/1.
        config.TARGET_COL: pa.Column(
            nullable=True,
            checks=pa.Check(lambda s: s.isna() | s.isin([0, 1])),
        ),
        **{
            col: pa.Column(nullable=False, checks=pa.Check.ge(0)) for col in COALESCED_COUNT_COLUMNS
        },
        r"^has_.*_history$": pa.Column(bool, nullable=False, regex=True),
    },
    strict=False,
    coerce=False,
)


def validate_mart(df):
    """Validates the full mart against MART_SCHEMA, collecting every
    violation (not just the first) before raising
    `pandera.errors.SchemaErrors` - see that schema's docstring for what's
    actually checked and why.
    """
    return MART_SCHEMA.validate(df, lazy=True)
